name: cognito deployment

on:
  push:
    branches: [ main ]
    paths:
      - "infra/**"
jobs:

  build:

    name: install Terraform and deploy
    runs-on: ubuntu-latest


    steps:

      - name: Check out code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION}}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Deploy Terraform for AWS config
        run: |
          cd infra
          terraform init
          terraform plan
          terraform apply -auto-approve